FROM elasticsearch:5.4.3

RUN cd plugins && wget https://github.com/mrkamel/sort-script/releases/download/untagged-27ee990946456c5d53b1/sort-script.tar.gz && tar xzf sort-script.tar.gz && rm sort-script.tar.gz
